version: "3.8"

services:
  connections-db:
    image: neo4j
    container_name: connections-db
    environment:
      - NEO4J_AUTH=neo4j/password  # Set your username and password
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    volumes:
      - connections-db-data:/data  # Persist data
    networks:
      - blog-hub-network

  discovery-server:
    image: luffy010/blog-hub/discovery-server
    container_name: discovery-server
    networks:
      - blog-hub-network
    ports:
      - "8761:8761"

  connections-service:
    image: luffy010/blog-hub/connections-service
    container_name: connections-service
    networks:
      - blog-hub-network
    depends_on:
      - discovery-server
      - connections-db

  api-gateway:
    image: luffy010/blog-hub/api-gateway
    container_name: api-gateway
    networks:
      - blog-hub-network
    ports:
      - "8080:8080"  # Make sure this port mapping exists
    environment:
      - SERVER_PORT=8080  # Explicitly set the port

networks:
  blog-hub-network:

volumes:
  connections-db-data:
